### ISSUE TITLE
Empty OBJ import, STL of the same file works fine

### ISSUE THREAD

**Issue by EmJay276** [sgsellan/gpytoolbox#67]
I tried to import some models from the [Engineering Shape Benchmark (ESB)](https://engineering.purdue.edu/cdesign/wp/downloads/)

For example `backdoor.obj` and `backdoor1.obj` from the [Flat-Thin Wallcomponents.tar.gz](https://engineering.purdue.edu/cdesign/wp/wp-content/uploads/2012/10/Flat-Thin-Wallcomponents.tar.gz) 
But the imported shape using the `.obj` type is `(0, 0)`.

Importing the STL file works fine.

**Comment by EmJay276** [comment]
Here the minimal example, `reader='Python'` returns `None`, while `reader='C++'` returns a numpy array with shape `(0,0)`

This should propably also be the same type. I would prefer a numpy array with shape `(0,0)`. If you agree, I can create a PR.

[backdoor_import.zip](https://github.com/sgsellan/gpytoolbox/files/10843298/backdoor_import.zip)

```
import gpytoolbox as gpy

u_stl, v_stl = gpy.read_mesh(r'backdoor.stl')
u_obj_c, v_obj_c = gpy.read_mesh(r'backdoor.obj', reader='C++')
u_obj_py, v_obj_py = gpy.read_mesh(r'backdoor.obj', reader='Python')

print(f"STL import: {u_stl.shape = }, {v_stl.shape = }")
print(f"OBJ import C++: {u_obj_c.shape = }, {v_obj_c.shape = }")
print(f"OBJ import Python {u_obj_py = }, {v_obj_py = }")
```

Result
```
STL import: u_stl.shape = (1368, 3), v_stl.shape = (2736, 3)
OBJ import C++: u_obj_c.shape = (0, 0), v_obj_c.shape = (0, 0)
OBJ import Python u_obj_py = None, v_obj_py = None
```

**Comment by sgsellan** [comment]
Woah! Okay, this file just seems corrupted. If you open it, e.g., in a text editor, you see the first lines are
```
2.629650..0.696604..0.689948..
242
276
599
809
936
1006
1223
1333
1313
1459
1406
1349
1409
1599
1723
1606
1833
1616
1653
1706
```

A usual obj files goes line by line and includes a string that determines the nature of each line, like
```
v -15.557107999999999 7.1158900000000003 -14.31406
v -15.557159 7.1158539999999997 -14.400069999999999
v 17.406731000000001 8.0585679999999993 -14.420237
v 17.406783999999998 8.0586029999999997 -14.334227
v -15.556960999999999 7.1409450000000003 -14.105993
v 17.406998000000002 8.1641180000000002 -14.126192
```

So something seems wrong with this obj file, but apparently the wrong formatting was not caught by any of our exceptions in `read_mesh`. It's probably a good idea to ping @odedstein , who wrote the obj readers.

@odedstein , do you think we should change the behaviour of `read_mesh` to catch this case?

**Comment by EmJay276** [comment]
Some addition:
The Engineering Shape Benchmark (ESB) is a quite common dataset used in several publications.
Citations of the paper developing this dataset: 258

**Comment by odedstein** [comment]
Thanks for the issue report, @EmJay276.

I agree with @sgsellan . This is a weird OBJ file for the text-only version of the OBJ format. When I try to import it in blender, it also doesn't seem to produce a meaningful import.
I'm not an expert on the OBJ specification, but this looks like an invalid OBJ file to me.

As far as behavior goes: I think that our OBJ reader should ideally recognize invalid OBJs and inform the caller. My preferred behavior actually would be to raise a catchable Python exception. The OBJ reader does not currently do this consistently (the python reader just has asserts). I think the entire OBJ reader should be overhauled so that C++ and Python parts have the same behavior on error, and that behavior should be a catchable exception.
This somehow seems more Pythonic to me than returning `None` or an empty array without further context telling me why the operation failed. I'd love to hear what you think @sgsellan @EmJay276 .

I can put this on the todo list, or @EmJay276, you can do it if you want to (no pressure though, I'm just mentioning it because you offered to make a PR earlier).

**Comment by AAA-Fei** [comment]
from gpytoolbox_bindings_copyleft import _swept_volume_impl
ImportError: DLL load failed while importing gpytoolbox_bindings_copyleft: 找不到指定的模块。

**Comment by sgsellan** [comment]
Hi @AAA-Fei ! That seems like an unrelated problem. Would you mind creating a new issue with it?

Silvia

**Comment by sgsellan** [comment]
I am closing this issue since it seems like the mesh reading issue was related to the file and not gpytoolbox, and the import problem mentioned by @AAA-Fei is dealt with in a different issue.
