### ISSUE TITLE
Marching Square gives zigzag lines 

### ISSUE THREAD

**Issue by iszihan** [sgsellan/gpytoolbox#86]
Hello, I'm using marching square function on a planar slice of sdf values, but am getting weird zigzag lines in the output. Here is the [link](https://drive.google.com/drive/folders/11F7_-aIY_grVPyucYDfGtjvK2CM2MwiW?usp=sharing) to the sdf value and a minimal script that reproduces the image below. 
![image](https://github.com/sgsellan/gpytoolbox/assets/36280571/a2698e6c-a51b-42ff-b8d8-2fe0a23cf11a)

Thank you in advance for looking into it!

**Comment by sgsellan** [comment]
Sorry for the delay in getting to this. Turns out, it was a much simpler problem than I expected. The list of vertices that you receive from `marching_squares` are not sorted; i.e., you cannot plot them with `plt.plot(V[:,0],V[:,1])`. Instead, the polyline is given with a list of edges, in a style mirroring how we deal with meshes. If you run
```python
V, E = gpytoolbox.marching_squares(sdf.reshape(-1,),np.c_[X.flatten(),Y.flatten()],nx,ny)
for i in range(E.shape[0]):
            plt.plot([V[E[i,0],0],V[E[i,1],0]],
                     [V[E[i,0],1],V[E[i,1],1]],
                     'k-')
```
you'll get the surface you want. I will push a quick commit making this clearer in the documentation
